//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServidorAhorcadoService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HONEYBUNNY\\SQLEXPRESS05;Initial Catalog=JuegoAhorcado;Integrated Secu" +
            "rity=True;Encrypt=True;TrustServerCertificate=True")]
        public string JuegoAhorcadoConnectionStringLilly {
            get {
                return ((string)(this["JuegoAhorcadoConnectionStringLilly"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HONEYBUNNY\\SQLEXPRESS05;Initial Catalog=JuegoAhorcado;Integrated Secu" +
            "rity=True;Encrypt=True;Trust Server Certificate=True")]
        public string JuegoAhorcadoConnectionString {
            get {
                return ((string)(this["JuegoAhorcadoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KIDA\\SQLEXPRESS;Initial Catalog=JuegoAhorcado;Integrated Security=Tru" +
            "e;TrustServerCertificate=True")]
        public string JuegoAhorcadoConnectionString1 {
            get {
                return ((string)(this["JuegoAhorcadoConnectionString1"]));
            }
        }
    }
}
